services:
  app:
    container_name: mind-forge-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=production
  redis:
    container_name: mind-forge-redis
    image: redis:7.4-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
